apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          # enter the path to your image, be sure to include the correct region prefix
          image: <Region-Prefix-Name>/<your-tenancy-namespace>/customapp:custom>
          ports:
            - containerPort: 80
      imagePullSecrets:
        # enter the name of the secret you created
        - name: newsecret
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: hello
